### ISSUE TITLE
Displaying Results with Adjusted Cell Boundaries in Napari

### ISSUE THREAD

**Issue by SanoKyohei** [Nanostring-Biostats/CosMx-Analysis-Scratch-Space#130]
Using methods like Baysor or Proseg, I modified the conventional cell boundaries and determined cell types based on the adjusted boundaries. I would like to display these results in Napari, but I am unsure how to proceed. 
How can I achieve this?

[Additional Information]
We have already adjusted the output format to align with the traditional CosMx format. Specifically, we have created new tx_file.csv, exprMat_file.csv, metadata_file.csv, and CellLabels Images based on the updated cell boundaries.

Due to the complexity of the new CosMx output files, we are unsure which parts of the output files need to be modified to reflect the changes in segmentation and cell IDs. We would appreciate guidance on this matter.

**Comment by eveilyeverafter** [comment]
Take a look at the CellLabels_FOV*.tif files. The cell assignments will be present as integers. 

<img width="1399" alt="image" src="https://github.com/user-attachments/assets/c3879785-6e98-47c9-b785-617af98a74a6">

**Comment by eveilyeverafter** [comment]
Did this suggestion help?

**Comment by SanoKyohei** [comment]
Sorry I forgot to reply. 
It helps a lot. Thank you very much

**Comment by sam-mick** [comment]
Hi, I'm trying to do the same thing - re-ran segmentation with Baysor and now want to view segmentation in Napari. 

I cannot figure out the steps of this for the life of me, previously I got the nice exported data off of AtoMx working with the napari-cosmx plugin which looks great - I'd love to see the new segmentation overlaid with the same sort of data (segmentation over channels like CD45).

Seems easy to generate the tx_file.csv & exprMat_file.csv. Cannot figure out how to generate the metadata_file.csv, and CellLabels Images with outputs of Baysor - but then since it seems that CellStatsDir and AnalysisResults are used to load data in plugin would these even help?
