### ISSUE TITLE
build error with h5ad render

### ISSUE THREAD

**Issue by eveilyeverafter** [Nanostring-Biostats/CosMx-Analysis-Scratch-Space#78]
There's a build error with the h5ad post trying to use the reticulate package. This is causing the site to not render. 

<img width="630" alt="image" src="https://github.com/Nanostring-Biostats/CosMx-Analysis-Scratch-Space/assets/5805450/1269ab8e-c3f2-4377-aefb-7a675e9a769c">

I'm not sure what the error is but it might be the header/label that's used.

**Comment by lidanwu** [comment]
@eveilyeverafter , the build error is because [your commit ](https://github.com/Nanostring-Biostats/CosMx-Analysis-Scratch-Space/commit/5829a56c3fc6daf74b17fe85742f1ef8ee348556#diff-0a4513e8dc7e92cfc41839907ae36b739c44d06cd3323735b29423ce4b8c9887L312) has deleted the `reticulate` package and its dependency from the `renv.lock` file. You need to add it back to resolve this.

**Comment by eveilyeverafter** [comment]
You're correct! I reverted that commit c7bc7e63074d3d62cc4189472b917a06d4c9f62d and it is working. Thank you.
